In [ ]:
import numpy as np

In [55]:
arr = np.random.randint(1,450,500)
arr
# filter all those item that are less than 100

array([120, 432, 238, 439, 289, 254, 392, 189, 302, 307, 237,  54,   8,
       432,  65, 228, 218, 287, 118,  86, 407, 298, 406, 165, 218, 217,
       286, 318, 112, 136, 397, 397, 244,  45, 202,  19, 110, 270,  18,
       186, 249,  60, 355, 315,  28, 327, 347,   2, 226, 371, 215, 434,
        23,  87, 201,  69,  56,  13, 133, 317, 321, 392, 129, 265, 346,
       332, 125, 364, 310, 447,   7, 263, 203, 446, 172, 141, 343, 223,
       272,  32,  14, 226, 100, 360, 245, 338, 243, 267, 265,  95, 272,
       346, 318,  28, 431,  72, 395, 316, 229, 149,  40, 202, 439, 412,
       441, 245,  81, 289,  10, 419,  16, 298, 288, 221, 354, 254, 255,
       239, 150,  74, 375, 265, 145, 448, 156,  68, 188, 194, 367, 176,
       345, 209, 241, 433, 393, 441, 186,  27, 155, 287, 261, 427, 154,
       110, 354, 130, 133,  85, 142, 137, 154, 226, 181, 355, 288, 320,
       224, 150, 178, 104, 393, 301,  66,  83, 260, 344, 186, 344, 211,
       389, 286, 334, 283, 419, 150, 174,  72,  69, 187,  42, 31

In [ ]:
sum(arr < 100)

107

In [ ]:
arr[arr < 100]

array([53, 78, 98,  1, 22, 42, 77, 84, 73,  5, 36, 70, 57, 31, 51, 81, 19,
       15, 33, 96, 66, 67, 44, 40, 63, 55, 27, 36, 47, 48, 71, 67, 62, 60,
       96, 34, 38,  2, 56, 11, 12, 24, 62, 28, 22, 40, 93, 98, 88, 92, 92,
       91, 95, 48, 42, 62, 86, 71, 68, 43, 50, 10, 45,  8,  6, 89, 62, 39,
       43, 88, 66, 30, 44, 14, 12, 30, 58, 94, 59, 56, 87, 15, 97, 41, 72,
       60, 59,  5, 26, 63, 90, 39, 71, 84, 70,  9, 71, 17, 87, 12,  5, 53,
       93, 65, 46, 34, 26])

In [ ]:
len(arr[arr < 100])

107

### 2D array


In [ ]:
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
type(ls)

list

In [ ]:
arr2 = np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape
## 3 * 3
# 3rows and 3 columns

(3, 3)

In [ ]:

arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[0]  # row

array([1, 2, 3])

In [ ]:
arr2[2]   # row

array([7, 8, 9])

In [ ]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[-1]

array([7, 8, 9])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[-2:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[-2:,-3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
# 3D array
ls = [[[1, 2, 3], [4, 5, 6],
       [7, 8, 9]],[[1, 2, 3],
      [4, 5, 6], [7, 8, 9]],
       [[1, 2, 3], [4, 5, 6],
        [7, 8, 9]],[[1, 2, 3],
         [4, 5, 6], [7, 8, 9]]]
ls

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [ ]:
arr3 = np.array(ls)

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(4, 3, 3)

In [ ]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr3[ :,1:3,1:3 ]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [ ]:
arr3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3.reshape(36,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# argmin()  # min()
# argmax()  # max()

# argsort()  # sort()