In [1]:
import numpy as np 

In [2]:
np.__version__

'2.0.1'

In [3]:
arr = np.array([25,10,20,30,40,50,60])
arr 

array([25, 10, 20, 30, 40, 50, 60])

In [4]:
ls = [25,10,20,30,40,50,60]
arr = np.array(ls)
arr 

array([25, 10, 20, 30, 40, 50, 60])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

1

In [8]:
arr.size

7

In [9]:
len(arr) 

7

In [10]:
arr.shape 

(7,)

In [12]:
arr

array([25, 10, 20, 30, 40, 50, 60])

In [11]:
arr.dtype

dtype('int64')

In [17]:
arr = np.array([25,10,20,30,40,50,60,'Hello'])
arr 

array(['25', '10', '20', '30', '40', '50', '60', 'Hello'], dtype='<U21')

In [16]:
arr.dtype

dtype('float64')

In [19]:
arr = np.array([25,10,20,30,40,50,60])
arr 

array([25, 10, 20, 30, 40, 50, 60])

In [24]:
arr[-1: -4:-1]

array([60, 50, 40])

In [28]:
arr + 5 

array([30, 15, 25, 35, 45, 55, 65])

In [29]:
arr *  10 

array([250, 100, 200, 300, 400, 500, 600])

In [30]:
arr / 5 

array([ 5.,  2.,  4.,  6.,  8., 10., 12.])

In [31]:
min(arr)

np.int64(10)

In [32]:
max(arr)

np.int64(60)

In [34]:
sum(arr )

np.int64(235)

In [36]:
np.mean(arr)

np.float64(33.57142857142857)

In [37]:
np.median(arr)

np.float64(30.0)

In [38]:
import random 

In [62]:
random.randint(1,9,)  #  1 to 9         


9

In [67]:
arr = np.random.randint(1,450,500)
arr

array([291, 396, 111,  87, 135, 132, 239, 169, 221, 162, 176, 290, 401,
       219,   2, 347, 216, 218, 123, 364, 365, 403, 321, 213, 133, 225,
       364, 296, 333, 409, 216, 227, 408, 315, 283, 212, 381,  38,  82,
       277,   8, 246, 325, 369, 432, 365, 218, 272,  98, 101, 281,   7,
       167, 414, 314, 191, 412,  84, 128, 386, 206, 182, 432, 212, 220,
       420, 370, 364, 125, 341,  31, 173, 291,   5, 226, 138, 110, 360,
       263, 311,   6, 268,  84, 122, 245, 155, 210, 402, 149, 325, 345,
       436, 448, 131, 324, 318, 153, 393, 144, 429, 136, 175, 403, 121,
       145, 102, 182,  24, 218, 284, 102, 410, 265, 174,  77, 151, 429,
       159, 365, 124,  53, 283,  15, 328, 223, 309, 162, 286, 363, 238,
       314, 100, 406,  33, 172,  61,  32, 337, 382,  36, 327, 144, 348,
       229, 286, 448, 241, 175,   7, 219, 245, 143,   5,  26, 376, 258,
       101, 403, 144, 284, 354, 416, 395, 344,  56, 374, 438, 402, 106,
       138, 324, 182,  31, 348,  18, 332, 157, 417,  54,  15,  1

In [69]:
import random ,string

In [70]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [71]:
string.digits

'0123456789'

In [75]:
alpha = string.ascii_letters  + string.digits

In [76]:
random.choice()

['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789']

In [77]:
arr = np.random.randint(1,450,500)
arr

## try to calculate no of item that are less than 100   # try with differents 
## try to calculate no. of even count 


array([243, 250,  20,  28, 377, 421, 235,  81, 230,  87,  85,  70, 153,
        40, 357,  39, 220, 363, 187,  11, 153,  36, 107, 415, 287, 141,
       255, 398, 344, 393, 122, 207, 152,  30, 179, 332, 448, 313, 192,
       372, 120, 352, 312,  11, 288, 393, 188, 445, 187, 139, 386, 395,
       439, 287, 270, 265, 138, 420, 217, 161,  25, 160, 186, 422,  92,
       251,   4, 390, 330, 404, 262, 349, 130,  91, 442, 222, 399, 428,
        56, 185,   7, 152, 172, 368,  46, 265, 107,  16, 340, 296, 271,
       430,  75, 220, 411, 303,  26,   5, 149, 392, 278, 311, 121, 134,
       425, 139,  55, 288, 350, 176, 341,  25, 198, 415, 263, 389, 274,
       145, 362, 397, 347,   4, 226, 379,  62, 269, 383, 271, 408, 410,
       123, 141, 412, 441, 294, 201, 308, 409,  84, 337, 352, 264, 180,
       151,  44,  56,  32, 170, 395, 297,  71,  42, 367, 418, 227, 299,
       145,  74, 102,  91, 295, 443, 101, 406,  24,  19, 447, 328, 404,
       207,  90,  57, 199, 434, 331, 279, 165, 422, 189, 220, 11